publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - case-police
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  '@tsparticles/engine': true
  esbuild: true
  node-jq: true
  sharp: true
  unrs-resolver: true
  workerd: true
