name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set BASE_PATH for develop
        if: github.ref == 'refs/heads/develop'
        run: echo "BASE_PATH=${{ vars.BASE_PATH_STAGING }}" >> $GITHUB_ENV

      - name: Set BASE_PATH for main
        if: github.ref == 'refs/heads/main'
        run: echo "BASE_PATH=${{ vars.BASE_PATH_PRODUCTION }}" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: 'build/*'
          target: ${{ vars.SERVER_PATH }}${{ env.BASE_PATH }}
